Enhancement
atifjavaid267/Online-Marketplace-for-Selling-Scrape pull request #80
Opened 2023-06-03 07:22 UTC by atifjavaid267

- Refactor views code to remove extra spaces and add missing spaces etc.
- Move JS code to seperate files.
- Refactor the flow of apps action.
- Refactor the code for security.

2023-06-05 15:21 UTC, hassanakbar4 requested changes

2023-06-05 15:21 UTC, hassanakbar4 commented on app/models/notification.rb
> +    [notification, messages]
- Do we need to return notifications here? 
- Messages should not be filtered here.

2023-06-05 15:21 UTC, hassanakbar4 commented on app/models/notification.rb
> +    notification.update(count: 0, read: true) if notification
Need to check if count > 0

2023-06-05 15:21 UTC, hassanakbar4 commented on app/models/order.rb
>    def pickup_time_cannot_be_in_the_past
https://github.com/atifjavaid267/Online-Marketplace-for-Selling-Scrape/pull/80/files#diff-26bbec4be8ce33f60fa824e2bd29e6902e57541818578634bea06bce180b620eR32

Should be moved to scope

2023-06-05 15:21 UTC, hassanakbar4 commented on app/models/notification.rb
>    def self.new_notification(sender_id, receiver_id)
method name is not clear

2023-06-08 09:12 UTC, HassanAkbar commented on app/controllers/messages_controller.rb
>      return unless @message.save
Error handling

2023-06-08 09:12 UTC, HassanAkbar commented on app/controllers/users/unlocks_controller.rb
> -end
Break

2023-06-08 10:39 UTC, progammer743 commented on app/models/message.rb
> +    MessageBroadcaster.new(self, order).broadcast_room_channel
Ideal Service
https://medium.com/selleo/essential-rubyonrails-patterns-part-1-service-objects-1af9f9573ca1

2023-06-12 07:00 UTC, HassanAkbar commented on app/channels/message_channel.rb
> +    stream_from "message_channel_#{params[:room_id]}"
Why RoomID ?

2023-06-12 07:00 UTC, HassanAkbar commented on app/javascript/channels/notification_channel.js
> +      const messageURL = `/orders/${orderID}/messages/new`;
Either use orderID or remove it

2023-06-12 07:00 UTC, HassanAkbar commented on app/javascript/channels/notification_channel.js
> +      const messageURL = `/orders/${orderID}/messages/new`;
Nested route

2023-06-12 07:00 UTC, HassanAkbar commented on app/models/notification.rb
> +  end
Method not needed ?

2023-06-12 07:00 UTC, HassanAkbar commented on app/models/notification.rb
> +    notification = find_by(receiver_id: current_user_id, sender_id:)
1. Method name?
2. We should make an association in current_user for notifications using `reciever_id` as foreign_key
3. Scope

2023-10-03 09:06 UTC, merged